### ISSUE TITLE
Report is blank

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/vscode-solidity-metrics#1]
Often when I generate a report, the output is blank. 

![image](https://user-images.githubusercontent.com/23033765/58569134-876b9c00-8203-11e9-9cd0-ff5438c1a2d3.png)

It seems to have to do with the size of the project, but I can't reliably reproduce it yet. But I'll open this for future reporting.

**Comment by tintinweb** [comment]
reopened: vscode issue -> https://github.com/microsoft/vscode/issues/89038

**Comment by tintinweb** [comment]
should be fixed with the latest vscode update.

**Comment by bingen** [comment]
It still happens to me (Linux, VSCode v1.49.1 and Solidity Metrics v0.0.11). Closing and opening didn’t help, the workaround I used was to right-click on blank metrics tab, then “Export current metrics report” and then open the generated html file with a browser.

**Comment by tintinweb** [comment]
thanks for the report @bingen! This is actually a different issue that we'll track here: https://github.com/ConsenSys/vscode-solidity-metrics/issues/6.

I've just published v0.0.12 addressing this issue.

cheers 🙌
