### ISSUE TITLE
State supported programming languages somewhere

### ISSUE THREAD

**Issue by micgro42** [ConsenSys/vscode-solidity-metrics#4]
Please state somewhere, ideally also on the extension page that is visible in VSCode, which programming languages this plugin supports. Is it only for JS/TS? PHP? Java/DotNet? Ruby? I have still no idea.

**Comment by tintinweb** [comment]
The extension creates code metrics reports for the [solidity](https://solidity.readthedocs.io/en/v0.6.11/) smart contract programming language. It kind of is in the extension's name 😅 But it just occurred to me that if you don't know the solidity language the word `solidity` might sound like part of a brand or so. Updated the readme to make it more clear. Thanks for the report!

--> https://github.com/ConsenSys/vscode-solidity-metrics/commit/a3fb3238c3d836d2c0b10e43fd42eb4745eee7c5

cheers,
tin

**Comment by micgro42** [comment]
That is exactly what happened. I expected it to somewhat create metrics about how solid (or SOLID) my code is.
Thank you for making it more explicit 🙏
