### ISSUE TITLE
Complexity score

### ISSUE THREAD

**Issue by mstad** [ConsenSys/vscode-solidity-metrics#8]
What is the calculation complexity based on (McCabe, Halstead, funtion points, other...)?

**Comment by GNSPS** [comment]
It uses McCabe's cyclomatic complexity plus a weighted average of a number of other metrics that our auditing team has considered to be defining in the amount of effort that goes into understanding a certain system (i.e., usage of assembly, usage of certain opcodes, etc.)

**Comment by mstad** [comment]
I kindly ask you if it is possible to have more specific detail about other parameters added to McCabe's cyclomatic complexity. Moreover, where could I find a deep explanation of  other parameters (e.g. as nsloc=standard sloc meaning?)
Thanks in advance.

**Comment by tintinweb** [comment]
Hey @mstad,

The complexity scoring system is a custom implementation that assigns a score to certain complexity increasing statements. This is not following standards while still producing a good initial overview of the complexity of functions.

The scores are hardcoded and defined here: https://github.com/ConsenSys/solidity-metrics/blob/master/src/metrics.js#L67-L88

Branches, Calls, public|payable| interfaces, loops, assembly, amount of state variables, ... are currently tracked as adding complexity to the codebase.

Normalizes source lines of code are produced by https://www.npmjs.com/package/sloc.

cheers,
tin

**Comment by GNSPS** [comment]
Hey @mstad 👋 

Let us know if you need these metrics for some research work you are currently taking on and if we can collaborate somehow in getting it to fruition. 😄 🙏 

A better place to have a more structured initial talk is probably an email thread.

Could you please shoot us an email to diligence@consensys.net with some details on how we can help you further?

**Comment by mstad** [comment]
Hey @GNSPS. 
![image](https://user-images.githubusercontent.com/63902230/105860544-fc513380-5fed-11eb-819b-718eafc811d7.png)

I send you soon an e-mail with some details.
